/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicPostsRouteImport } from './routes/(public)/posts'
import { Route as publicHomeRouteImport } from './routes/(public)/home'
import { Route as publicPostPostIdRouteImport } from './routes/(public)/post.$postId'

const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicPostsRoute = publicPostsRouteImport.update({
  id: '/(public)/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const publicHomeRoute = publicHomeRouteImport.update({
  id: '/(public)/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const publicPostPostIdRoute = publicPostPostIdRouteImport.update({
  id: '/(public)/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/home': typeof publicHomeRoute
  '/posts': typeof publicPostsRoute
  '/': typeof publicIndexRoute
  '/post/$postId': typeof publicPostPostIdRoute
}
export interface FileRoutesByTo {
  '/home': typeof publicHomeRoute
  '/posts': typeof publicPostsRoute
  '/': typeof publicIndexRoute
  '/post/$postId': typeof publicPostPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)/home': typeof publicHomeRoute
  '/(public)/posts': typeof publicPostsRoute
  '/(public)/': typeof publicIndexRoute
  '/(public)/post/$postId': typeof publicPostPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/home' | '/posts' | '/' | '/post/$postId'
  fileRoutesByTo: FileRoutesByTo
  to: '/home' | '/posts' | '/' | '/post/$postId'
  id:
    | '__root__'
    | '/(public)/home'
    | '/(public)/posts'
    | '/(public)/'
    | '/(public)/post/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicHomeRoute: typeof publicHomeRoute
  publicPostsRoute: typeof publicPostsRoute
  publicIndexRoute: typeof publicIndexRoute
  publicPostPostIdRoute: typeof publicPostPostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/posts': {
      id: '/(public)/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof publicPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/home': {
      id: '/(public)/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof publicHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/post/$postId': {
      id: '/(public)/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof publicPostPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  publicHomeRoute: publicHomeRoute,
  publicPostsRoute: publicPostsRoute,
  publicIndexRoute: publicIndexRoute,
  publicPostPostIdRoute: publicPostPostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
